# Generated by Django 2.2.4 on 2020-08-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote',
            new_name='quotedby',
        ),
    ]
