# Generated by Django 2.2.4 on 2020-08-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_auto_20200825_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='description',
            field=models.CharField(max_length=264),
        ),
    ]
