# Generated by Django 2.2.4 on 2020-08-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0003_auto_20200825_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='description',
            new_name='quotedescription',
        ),
    ]
